addons:
  postgresql: "9.6"
cache: cargo
language: rust
notifications:
  email:
    on_success: never
rust:
  - nightly
  - stable
# Faster container-based builds
sudo: false

env:
  - DATABASE_URL=postgres://localhost/pod_core

before_script:
  - cargo install diesel_cli --no-default-features --features postgres
  - createdb pod_core
  - diesel migration run

script:
  - cargo test --verbose
