[package]
name = "podcore"
version = "0.1.0"
authors = ["Brandur <brandur@brandur.org>"]

[lib]
name = "podcore"
path = "src/lib.rs"

[[bin]]
name = "podcore-serve"
path = "src/bin/podcore-serve/main.rs"

[dependencies]
chrono = "0.4"
diesel = { version = "1.0.0-rc1", features = ["chrono", "postgres"] }
error-chain = { version = "*" }
futures = "0.1"
hyper = "0.11"

# This should really be 0.6.0, but unfortunately there appears to be a mismatch
# in which module the `Request` struct belongs. Hopefully `juniper_iron` will
# get this fixed at some point.
iron = "0.5.1"

# Likewise, `mount` is also locked to something old to support old `iron`.
mount = "^0.3.0"

juniper = { version = "0.9.1" }
juniper_iron = { version = "0.1.1" }
lazy_static = "1.0"
quick-xml = "0.10.1"
r2d2 = { version = "*" }
r2d2-diesel = { version = "1.0.0-rc1" }
regex = "0.2"
rust-crypto = "^0.2"
serde = { version = "1.0.24" }
serde_derive = "*"
serde_json = { version = "1.0.8" }
slog = "*"
slog-async = "*"
slog-term = "*"
time = { version = "*" }
tokio-core = "0.1"
