apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: podcore-web
  labels:
    app: podcore-web
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: podcore-web
    spec:
      containers:
      - name: podcore
        image: gcr.io/podcore-194423/podcore:1.30
        command: ["/podcore", "web"]
        ports:
        - containerPort: 8083
        env:
        - name: CSRF_ORIGIN
          value: "http://podcore.brandur.org"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: DATABASE_URL
        # remember that this is per-replica
        - name: NUM_CONNECTIONS
          value: "5"
        - name: PODCORE_ENV
          value: "production"
        - name: PORT
          value: "8083"
        - name: RUST_BACKTRACE
          value: "1"
        - name: SENTRY_URL
          valueFrom:
            secretKeyRef:
              name: sentry-credentials
              key: SENTRY_URL
        readinessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=podcore-194423:us-central1:core=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudsql
          emptyDir:
