apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: podcore-clean
  labels:
    app: podcore-clean
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: podcore-clean
    spec:
      containers:
      - name: podcore
        image: gcr.io/podcore-194423/podcore:1.30
        command: ["/podcore", "clean"]
        env:

        # We're constraining maximum connections with `NUM_CONNECTIONS` so use
        # a relatively long connect timeout so threads don't timeout waiting
        # for a connection to be available. In seconds.
        - name: CONNECT_TIMEOUT
          value: "60"

        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: DATABASE_URL

        # The cleaner has lots of jobs that will run in parallel given enough
        # connections, but our connection limits are low, so constrain the
        # maximum number it uses. `CONNECT_TIMEOUT` must also be reasonably
        # large so that threads don't timeout waiting for a connection.
        - name: NUM_CONNECTIONS
          value: "2"

        - name: PODCORE_ENV
          value: "production"
        - name: RUST_BACKTRACE
          value: "1"
        - name: SENTRY_URL
          valueFrom:
            secretKeyRef:
              name: sentry-credentials
              key: SENTRY_URL
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=podcore-194423:us-central1:core=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudsql
          emptyDir:
